### ISSUE TITLE
Could you please explain the role of CandidateOutputLayer?

### ISSUE THREAD

**Issue by webeng** [adbrebs/rnn_reader#2]
Hi, 

I'm trying to figure out what's the role of the CandidateOutputLayer in the attention model? I've checked the racoon repo but I still don't get it.

Thanks in advance.

**Comment by adbrebs** [comment]
Sure!
- The model has to output one of the 512 possible entities. So the model has 512 output neurons.
- The answer of the question is present in the document. Therefore only x out of the 512 possible entities are present in the document and are thus potential candidates for the answer. That's why we have a candidate mask.

CandidateOutputLayer is making sure that the model only predicts entities present in the document by assigning very low outputs to the other entities.

**Comment by webeng** [comment]
Thank you for your reply.

No it makes a lot more sense to me.
